heat_template_version: 2013-05-23

description: >
  Deploiement sur une machine openstack de notre serveur python

parameters:
  key_name:
    type: string
    description: Name of an existing key pair to use for the server
    constraints:
      - custom_constraint: nova.keypair
    default: brandon
  flavor:
    type: string
    description: Flavor for the server to be created
    default: INF4410-mini
    constraints:
      - custom_constraint: nova.flavor
  image:
    type: string
    description: Image ID or image name to use for the server
    constraints:
      - custom_constraint: glance.image
    default: INF4410-Ubuntu-trusty-mini
  network_id: 
    type: string
    description: network to use
    default: 938775f1-1d27-4d35-a41d-e76eac6797db

resources:
  server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks: 
        - network: { get_param: network_id }
      user_data_format: RAW
      user_data: |
        #!/bin/bash
        curl https://raw.githubusercontent.com/houssemmh/INF8480-TP3/master/server.py | python
  floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: ext-net
  association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: {get_resource: floating_ip}
      server_id: {get_resource: server}


outputs:
  server_networks:
    description: The networks of the deployed server
    value: { get_attr: [server, networks] }
